# Generated by Django 5.2.17 on 2026-08-26 18:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('BORROWED', 'Borrowed'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue'), ('LOST', 'Lost')], db_index=True, default='BORROWED', max_length=20)),
                ('renewal_count', models.PositiveIntegerField(default=0)),
                ('max_renewals', models.PositiveIntegerField(default=2)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrowings', to='books.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrowings', to='members.member')),
            ],
            options={
                'ordering': ['-borrow_date'],
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('WAIVED', 'Waived')], db_index=True, default='PENDING', max_length=20)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('reason', models.CharField(default='Overdue book return', max_length=255)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrowing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='circulation.borrowing')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='books.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='members.member')),
            ],
            options={
                'ordering': ['priority', 'reservation_date'],
            },
        ),
        migrations.AddIndex(
            model_name='borrowing',
            index=models.Index(fields=['status'], name='circulation_status_23a5d4_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowing',
            index=models.Index(fields=['due_date'], name='circulation_due_dat_fd382e_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowing',
            index=models.Index(fields=['borrow_date'], name='circulation_borrow__c392be_idx'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['status'], name='circulation_status_4b4a84_idx'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['created_at'], name='circulation_created_02b5f6_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status'], name='circulation_status_a488dd_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['priority'], name='circulation_priorit_b0412d_idx'),
        ),
    ]
