# Generated by Django 5.2.17 on 2026-08-29 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', help_text='Alternative cover source: a publicly reachable image URL, used when no local cover image is uploaded.'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Set this to make the category a Sub-genre of another (parent) Genre.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='books.category', verbose_name='Parent Genre'),
        ),
    ]
