# Generated by Django 5.2.17 on 2026-08-26 18:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.TextField(blank=True)),
                ('membership_status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=20)),
                ('max_borrow_limit', models.PositiveIntegerField(default=5)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='members/qrcodes/')),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['member_code'], name='members_mem_member__4bf4cb_idx'), models.Index(fields=['email'], name='members_mem_email_afed21_idx'), models.Index(fields=['membership_status'], name='members_mem_members_6be344_idx')],
            },
        ),
    ]
