# Generated by Django 5.2.17 on 2026-08-26 19:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
